export const SLASH_COMMAND = {
  sbk: "sbk",
  check: "check",
  immune: "immune",
  ignore: "ignore",
  reset: "reset",
  menu: "menu",
} as const;

export const MUSIC_TEXT_COMMAND = {
  play: "play",
  np: "np",
  skip: "skip",
  skipAlias: "s",
  stop: "stop",
  queue: "queue",
  upload: "upload",
  ng: "ng",
  ngAlias: "ngword",
  help: "help",
  remove: "remove",
  removeAlias: "delete",
  limit: "limit",
  limitAlias: "max",
  disable: "disable",
  disableAlias: "d",
  enable: "enable",
  enableAlias: "e",
  repeat: "repeat",
  manage: "manage",
  volume: "vol",
  pause: "pause",
} as const;
